

CREATE TABLE ANS_ExamResult
(StudentName VARCHAR(70), 
 Subject     VARCHAR(20), 
 Marks       INT
);

SELECT * FROM ANS_ExamResult 


SELECT Studentname, 
       Subject, 
       Marks, 
       DENSE_RANK() OVER(ORDER BY Marks DESC) as DRank1
FROM ANS_ExamResult
ORDER BY DRank1;


SELECT Studentname, 
       Subject, 
       Marks, 
       DENSE_RANK() OVER(PARTITION BY Subject ORDER BY Marks DESC) Rank1
FROM ANS_ExamResult
ORDER BY Studentname, 
         Rank1;

-----Dense_Rank() funtion---    
SELECT
	*
FROM
	ANS_EMPLOYEES5

SELECT DENSE_RANK () OVER (ORDER BY SALARY DESC) AS DRNK,SALARY
FROM ANS_EMPLOYEES5  


SELECT RANK () OVER (ORDER BY SALARY DESC) AS DRNK,SALARY,DEPARTMENT_ID
FROM ANS_EMPLOYEES5
        
        
SELECT DENSE_RANK () OVER (PARTITION  BY DEPARTMENT_ID ORDER BY SALARY DESC) AS DRNK,SALARY,DEPARTMENT_ID
FROM ANS_EMPLOYEES5
--WHERE DEPARTMENT_ID=90;


WITH RESULTS AS(
SELECT DENSE_RANK () OVER ( ORDER BY SALARY DESC) AS DRNK,SALARY,DEPARTMENT_ID
FROM ANS_EMPLOYEES5)
SELECT TOP 2 SALARY, DRNK , DEPARTMENT_ID FROM RESULTS


WITH RESULTS AS(
SELECT DENSE_RANK () OVER (PARTITION  BY DEPARTMENT_ID ORDER BY SALARY DESC) AS DRNK,SALARY,DEPARTMENT_ID
FROM ANS_EMPLOYEES5)
SELECT TOP 2 SALARY, DRNK , DEPARTMENT_ID FROM RESULTS WHERE DEPARTMENT_ID=90



        


        
        


  
        
        
        
          
        
        
        
        
        
        




