--JOINS USING 3 TABLES---

CREATE TABLE ANS_DEPT (
EMP_ID INT,
DEP_ID INT)

INSERT INTO ANS_DEPT VALUES(101,1),
(102,2),(103,1),(104,2)
INSERT INTO ANS_DEPT VALUES(110,6)

SELECT * FROM ANS_EMPLOYEE1
SELECT * FROM ANS_ADDRESS 
SELECT * FROM ANS_DEPT

SELECT E.EMP_ID,E.NAME,A.CITY,A.COUNTRY,D.DEP_ID 
FROM ANS_EMPLOYEE1 AS E 
INNER JOIN ANS_ADDRESS A
ON E.ZIPCODE=A.ZIPCODE
INNER JOIN ANS_DEPT D
ON E.EMP_ID = D.EMP_ID 

SELECT E.EMP_ID,E.NAME,A.CITY,A.COUNTRY,D.DEP_ID 
FROM ANS_EMPLOYEE1 AS E 
INNER JOIN ANS_ADDRESS A
ON E.ZIPCODE=A.ZIPCODE
LEFT  JOIN ANS_DEPT D
ON E.EMP_ID = D.EMP_ID 

SELECT E.EMP_ID,E.NAME,A.CITY,A.COUNTRY,D.DEP_ID
FROM ANS_EMPLOYEE1 AS E 
RIGHT JOIN ANS_ADDRESS A
ON E.ZIPCODE=A.ZIPCODE
RIGHT JOIN ANS_DEPT D
ON E.EMP_ID = D.EMP_ID 
