

---views----

CREATE TABLE STUDENT
(
STUD_ID INT PRIMARY KEY,
STUD_NAME VARCHAR(20),
STUD_DOB DATE,
SUB_ID INT
)

DROP TABLE SUBJECT 

INSERT INTO STUDENT VALUES (2001,'JOHN','2001-01-15',1),
(2002,'RITHA','2000-05-13',2),
(2003,'RAMYA','2000-06-20',1),
(2004,'RICHARD','1999-06-22',3),
(2005,'MARY','1999-02-19',4),
(2006,'MILLY','2000-07-09',6)


CREATE TABLE SUBJECT
(
SUBJECT_ID INT PRIMARY KEY,
SUB_NAME VARCHAR(20),
ADVISOR_id int
);

INSERT INTO SUBJECT VALUES(1,'ECONOMICS',101),
(2,'ACCOUNTING',102)
,(3,'DATABASE',103),
(4,'JOUNALISM',104),
(5,'STATISTICS',101)


SELECT * FROM STUDENT
SELECT * FROM SUBJECT






-----Rank Functions---

CREATE TABLE EMPLOYEE_INFO (
	ID INT PRIMARY KEY,
	NAME varchar(20),
	SALARY decimal(8,3),
	MANAGER_ID INT,
	DEPT_ID INT
);

SELECT * FROM EMPLOYEE_INFO 


SELECT DENSE_RANK () OVER (ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID,ID,NAME
FROM EMPLOYEE_INFO;


SELECT RANK () OVER (ORDER BY SALARY DESC) AS RNK,SALARY,DEP_ID,ID ,NAME 
FROM EMPLOYEE_INFO ;
        
        
SELECT DENSE_RANK () OVER (PARTITION  BY DEP_ID ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID
FROM EMPLOYEE_INFO



WITH RESULTS AS(
SELECT DENSE_RANK () OVER ( ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID
FROM EMPLOYEE_INFO)
SELECT TOP 2 SALARY, DRNK , DEP_ID FROM RESULTS


WITH RESULTS AS(
SELECT DENSE_RANK () OVER (PARTITION  BY DEP_ID ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID
FROM EMPLOYEE_INFO
)
SELECT TOP 2 SALARY, DRNK , DEP_ID FROM RESULTS WHERE DEP_ID=100

SELECT ROW_NUMBER () OVER( PARTITION BY DEP_ID ORDER BY SALARY ) AS ROW_NUM, ID, NAME, SALARY 
FROM EMPLOYEE_INFO ei ;




WITH DEL_REC AS
(
SELECT *, ROW_NUMBER() OVER(PARTITION BY id ORDER BY id) as xy
from EMPLOYEE1

)
delete from DEL_REC where xy>1

SELECT * FROM EMPLOYEE1

delete from EMPLOYEE1 

CREATE TABLE EMPLOYEE1 (
	ID INT,
	NAME varchar(20),
	SALARY decimal(8,3),
	MANAGER_ID INT,
	DEPT_ID INT
);


INSERT INTO EMPLOYEE1 values(101,'MARY',20000,NULL,1)
INSERT INTO EMPLOYEE1 values(101,'MARY',20000,NULL,1)
INSERT INTO EMPLOYEE1 values(102,'VICKY',30000,101,1)
INSERT INTO EMPLOYEE1 values(102,'VICKY',30000,101,1)
INSERT INTO EMPLOYEE1 values(103,'RITHA',25000,101,2);







































