-----Rank Functions---

CREATE TABLE EMPLOYEES1(
	EMPLOYEE_ID INT
	NAME varchar(20),
	SALARY decimal(8,2) NULL,
	DEPARTMENT_ID INT
);

SELECT * FROM EMPLOYEE_INFO 


update EMPLOYEE_INFO SET SALARY =9000 WHERE ID=112

CREATE TABLE EMPLOYEE_INFO 
(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
SALARY DECIMAL(8,3),
MANAGER_ID INT,
DEP_ID INT);

SELECT DENSE_RANK () OVER (ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID,ID,NAME
FROM EMPLOYEE_INFO


INSERT INTO EMPLOYEE_INFO VALUES(103,'Rita',16000,101,90),
(104,'Mary',15000,102,90)

SELECT RANK () OVER (ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID
FROM EMPLOYEE_INFO 
        
        
SELECT DENSE_RANK () OVER (PARTITION  BY DEP_ID ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID
FROM EMPLOYEE_INFO
--WHERE DEPARTMENT_ID=90;


WITH RESULTS AS(
SELECT DENSE_RANK () OVER ( ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID
FROM EMPLOYEE_INFO)
SELECT TOP 2 SALARY, DRNK , DEP_ID FROM RESULTS


WITH RESULTS AS(
SELECT DENSE_RANK () OVER (PARTITION  BY DEP_ID ORDER BY SALARY DESC) AS DRNK,SALARY,DEP_ID
FROM EMPLOYEE_INFO)
SELECT TOP 2 SALARY, DRNK , DEP_ID FROM RESULTS WHERE DEP_ID=100



---views----

CREATE TABLE STUDENT
(
STUD_ID INT PRIMARY KEY,
STUD_NAME VARCHAR(20),
STUD_DOB DATE,
SUB_ID INT
)

DELETE FROM STUDENT 

INSERT INTO STUDENT VALUES (2001,'JOHN','2001-01-15',1),
(2002,'RITHA','2000-05-13',2),
(2003,'RAMYA','2000-06-20',1),
(2004,'RICHARD','1999-06-22',3),
(2005,'MARY','1999-02-19',4),
(2006,'MILLY','2000-07-09',6)


CREATE TABLE SUBJECT
(
SUBJECT_ID INT PRIMARY KEY,
SUB_NAME VARCHAR(20),
ADVISOR_id int
);

INSERT INTO SUBJECT VALUES(1,'ECONOMICS',101),
(2,'ACCOUNTING',102)
,(3,'DATABASE',103),
(4,'JOUNALISM',104),
(5,'STATISTICS',101)



SELECT * FROM STUDENT
SELECT * FROM SUBJECT







