--23-09-2022--
---Slowly changind dimensions--
CREATE TABLE EMPLOYEE
(
ID INT,
NAME VARCHAR(20),
PLACE VARCHAR(20),
SALARY INT,
DEPT VARCHAR(10),
START_DATE DATE,
END_DATE DATE,
STATUS VARCHAR(30));

INSERT INTO EMPLOYEE VALUES
(102,'RITHA','Karnataka',30000,'IT',NULL,NULL,' ')

(101,'JOHN','Mumbai',20000,'HR',NULL,NULL,' '); 


SELECT * FROM EMPLOYEE aet 

DELETE FROM EMPLOYEE_T;

 

UPDATE EMPLOYEE  SET DEPT='IT',PLACE='Chennai' WHERE ID=102;

UPDATE EMPLOYEE  SET PLACE='Pune' WHERE ID=102;

CREATE TABLE EMPLOYEE_T
(
ID INT,
NAME VARCHAR(20),
PLACE VARCHAR(20),
SALARY INT,
DEPT VARCHAR(10),
START_DATE DATE,
END_DATE DATE,
STATUS VARCHAR(30));


SELECT * from EMPLOYEE_T


UPDATE EMPLOYEE  SET PLACE='Punjab' WHERE ID=102;

SELECT distinct city from HEALTH_RECORD hr 

select * from HEALTH_RECORD hr where Segment ='Consumer' and City in('Orange','Baltimore')

SELECT DISTINCT CITY FROM HEALTH_RECORD;