
--COPY COLUMNS--

CREATE TABLE ANS_PRODUCT(
NAME VARCHAR(50),
COST FLOAT,
COLOR VARCHAR(50),
DAYS_TO_MANUFACTURER INT
);

INSERT INTO ANS_PRODUCT VALUES('SHIRT',700,'BLACK',5),
('TOP',1000,'PINK',4),
('SNEAKERS',2000,'WHITE',10);


CREATE TABLE ANS_PRODUCT_TARGET(
NAME VARCHAR(50),
COST FLOAT,
COLOR VARCHAR(50),
DAYS_TO_MANUFACTURER INT,
PRODUCT_COST FLOAT,
PRODUCT_COLOR VARCHAR(50)
);

TRUNCATE table ANS_PRODUCT_TARGET ;


SELECT * FROM ANS_PRODUCT_TARGET


---DERIVED COLUMN CONVERSATION----
CREATE TABLE ANS_TARGET_EMP
(
ID INT,
FIRSTNAME VARCHAR(40),
LASTNAME VARCHAR(40),
FULLNAME VARCHAR(100),
MOBILE VARCHAR(20),
DEPT VARCHAR(50));


SELECT * FROM ANS_TARGET_EMP E



CREATE TABLE ANS_HEALTH_RECORD
(
YEAR INT,
State VARCHAR(300),
HAI VARCHAR(300),
OPERATIVE_PROCEDURE VARCHAR(300),
FACILITY_ID INT,
FACILITY_NAME VARCHAR(300),
HOSPITAL_CATEGORY_RISK VARCHAR(300),
HOSPITAL_TYPE VARCHAR(300),
COUNTRY VARCHAR(300),
PROCEDURE_COUNT INT,
INFECTION_COUNT INT,
PREDICTED_INFECTION_COUNT FLOAT,
SIR FLOAT,
SIR_CI_95_LOWER_LIMIT FLOAT,
SIR_CI_95_UPPER_LIMIT FLOAT,
COMPARISION VARCHAR(300),
SIR_2015 FLOAT,
ONTRACK_TOWARD_2022_GOAL VARCHAR(300),
NOTES VARCHAR(300)
);

SELECT * FROM ANS_HEALTH_RECORD 