-----15-09-2022


CREATE TABLE ANS_STORE(
ROW_ID INTEGER,
ORDER_ID VARCHAR(100),
ORDER_DATE VARCHAR(100),
SHIP_DATE VARCHAR(100),
SHIP_MODE VARCHAR(100),
CUSTOMER_ID VARCHAR(100),
CUSTOMER_NAME VARCHAR(100),
SEGMENT VARCHAR(100),
COUNTRY VARCHAR(100),
CITY VARCHAR(100),
STATE VARCHAR(100),
POSTAL_CODE INTEGER,
REGION VARCHAR(100),
PRODUCT_ID VARCHAR(100),
CATEGORY VARCHAR(100),
SUB_CATEGORY VARCHAR(100),
PRODUCT_NAME VARCHAR(100),
SALES FLOAT,
QUANTITY INTEGER,
DISCOUNT FLOAT,
PROFIT FLOAT);

DELETE FROM ANS_STORE

TRUNCATE TABLE  ANS_STORE

SELECT * FROM ANS_STORE


CREATE TABLE ANS_STORE1(
ROW_ID VARCHAR(300),
ORDER_ID VARCHAR(300),
ORDER_DATE date,
SHIP_DATE date,
SHIP_MODE VARCHAR(300),
CUSTOMER_ID VARCHAR(300),
CUSTOMER_NAME VARCHAR(300),
SEGMENT VARCHAR(300),
COUNTRY VARCHAR(300),
CITY VARCHAR(300),
STATE VARCHAR(300),
POSTAL_CODE VARCHAR(300),
REGION VARCHAR(300),
PRODUCT_ID VARCHAR(300),
CATEGORY VARCHAR(300),
SUB_CATEGORY VARCHAR(300),
PRODUCT_NAME VARCHAR(300),
SALES VARCHAR(300),
QUANTITY VARCHAR(300),
DISCOUNT VARCHAR(300),
PROFIT VARCHAR(300));



SELECT * from ANS_STORE1

CREATE TABLE ANS_LOCATION1
(
EMPLOYEE_NO INT,
LOC_ID INT,
CITY VARCHAR(50),
PINCODE INT
);

INSERT INTO ANS_LOCATION1 VALUES(2001,1,'BANGALORE',567345);
INSERT INTO ANS_LOCATION1 VALUES(1001,2,'MANGALORE',567342);
INSERT INTO ANS_LOCATION1 VALUES(2002,3,'SHIMOGA',547345);
INSERT INTO ANS_LOCATION1 VALUES(1002,4,'HUBLI',435345);
INSERT INTO ANS_LOCATION1 VALUES(2002,5,'DHARWAD',566345);

CREATE TABLE ANS_LOCATION2
(
EMPLOYEE_NO INT,
LOC_ID INT,
CITY VARCHAR(50),
PINCODE INT
);

INSERT INTO ANS_LOCATION2 VALUES(2001,1,'BANGALORE',567345);
INSERT INTO ANS_LOCATION2 VALUES(1001,2,'MANGALORE',567342);
INSERT INTO ANS_LOCATION2 VALUES(2002,3,'SHIMOGA',547345);
INSERT INTO ANS_LOCATION2 VALUES(1002,4,'HUBLI',435345);

SELECT * FROM ANS_LOCATION al 

CREATE TABLE ANS_LOCATION3
(
EMPLOYEE_NO INT,
LOC_ID INT,
CITY VARCHAR(50),
PINCODE INT );

SELECT * FROM ANS_LOCATION3

TRUNCATE TABLE ANS_LOCATION3


----16-09-22---

SELECT * FROM ANS_STUD_DETAILS

----task 1 union all--

create table ANS_NEWEMP
( id INTEGER,
name VARCHAR(50),
age INTEGER,
department VARCHAR(50)

);

SELECT * FROM ANS_NEWEMP w

TRUNCATE TABLE ANS_NEWEMP ;




--task 2---


create table ANS_SourceEMP
( id INTEGER,
name VARCHAR(50),
age INTEGER,
department VARCHAR(50)

);

INSERT INTO ANS_SourceEMP VALUES(11,'sanjay',30,'Sales'),
(12,'ramya',25,'IT');


--task3--
create table ANS_Source1EMP
( id INTEGER,
name VARCHAR(50),
age INTEGER,
department VARCHAR(50)

);


INSERT INTO ANS_Source1EMP VALUES(11,'sanjay',30,'Sales'),
(12,'ramya',25,'IT');

create table ANS_Source2EMP
( id INTEGER,
name VARCHAR(50),
age INTEGER,
department VARCHAR(50)

);


INSERT INTO ANS_Source2EMP VALUES(21,'Mary',31,'HR'),
(25,'Rikita',25,'IT');

create table ANS_Source3EMP
( id INTEGER,
name VARCHAR(50),
age INTEGER,
department VARCHAR(50)

);


INSERT INTO ANS_Source3EMP VALUES(31,'Jay',33,'Sales'),
(22,'john',23,'Finance');

--Conditional Split--


CREATE TABLE ANS_STUD_SOURCE
(
ID INTEGER,
NAME VARCHAR(50),
MARKS INTEGER
);
INSERT INTO ANS_STUD_SOURCE VALUES(1,'Sahil',50),
(2,'Meera',38),
(3,'John',78),
(4,'Neha',34),
(5,'Ajay',97),
(6,'Nithya',67),
(7,'Mary',88)

CREATE TABLE ANS_STUD_F
(
ID INTEGER,
NAME VARCHAR(50),
MARKS INTEGER);


CREATE TABLE ANS_STUD_P
(
ID INTEGER,
NAME VARCHAR(50),
MARKS INTEGER);

CREATE TABLE ANS_STUD_FD
(
ID INTEGER,
NAME VARCHAR(50),
MARKS INTEGER);

 
SELECT * FROM ANS_STUD_P

SELECT * FROM ANS_STUD_FD D
 

TRUNCATE TABLE ANS_STUD_F;
TRUNCATE TABLE ANS_STUD_FD;
TRUNCATE TABLE ANS_STUD_P;

CREATE TABLE ANS_SALES_YR_2020(
SALES_ID INTEGER,
PRODUCT_NAME VARCHAR(50),
QUANTITY INTEGER,
YEAR INTEGER);

CREATE TABLE ANS_SALES_YR_2021(
SALES_ID INTEGER,
PRODUCT_NAME VARCHAR(50),
QUANTITY INTEGER,
YEAR INTEGER);

CREATE TABLE ANS_SALES_YR_2022(
SALES_ID INTEGER,
PRODUCT_NAME VARCHAR(50),
QUANTITY INTEGER,
YEAR INTEGER);


SELECT * FROM ANS_SALES_YR_2022 

TRUNCATE TABLE ANS_SALES_YR_2020;
TRUNCATE TABLE ANS_SALES_YR_2021;
TRUNCATE TABLE ANS_SALES_YR_2022;